project:
  type: website

website:
  title: "Powdery Mildew - Análise de Dados"
  search: true

  navbar:
    left:
      - text: "Sobre"
        file: index.qmd
        icon: info-circle
      - text: "Obtenção de Dados"
        file: obtencao_dados.qmd
        icon: download
      - text: "Análise"
        file: analise.qmd
        icon: chart-line
    right:
      - text: "Abner"
        icon: github
        href: https://github.com/abnerrmp
      - text: "Daiane"
        icon: github
        href: https://github.com/daianerf
      - text: "Maria"
        icon: github
        href: https://github.com/izabelalmeidal

  page-footer:
    left: "© 2025 - Abner Reurisson M. Palhares, Daiane R. Fernandes e Maria Izabel A. Leite"
    right: "Feito com [Quarto](https://quarto.org)"

format:
  html:
    theme: minty
    toc: true
    page-layout: full
    highlight-style: github
    code-copy: true
    code-overflow: wrap
    execute:
      warning: false
      message: false